sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
env:
  - DOCKER_COMPOSE_VERSION=2.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - docker-compose -v
before_script:
  - docker-compose up --build -d
after_script:
  - docker-compose down



